version: 2.1

orbs:
  github-ssh-key: kelvintaywl/github-ssh-key-checkup@0.2

jobs:
  check:
    parameters:
      docker-image:
        type: string
    docker:
      - image: << parameters.docker-image >>
    resource_class: small
    steps:
      # NOTE: I chose not to checkout since CircleCI created an non-RSA deploy key by default,
      # and using checkout will check out this key into the system.
      # - checkout

      # Instead, I have added an RSA key as part of the project here,
      # and will check out this key instead.
      - run:
          name: Update SSH Known Hosts
          command: |
            # See https://circleci.com/docs/2.0/gh-bb-integration/#establishing-the-authenticity-of-an-ssh-host
            mkdir -p ~/.ssh

            echo 'github.com ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ==
            bitbucket.org ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAubiN81eDcafrgMeLzaFPsw2kNvEcqTKl/VqLat/MaB33pZy0y3rJZtnqwR2qOOvbwKZYKiEO1O6VqNEBxKvJJelCq0dTXWT5pbO2gDXC6h6QDXCaHo6pOHGPUy+YBaGQRGuSusMEASYiWunYN0vCAI8QaXnWMXNMdFP3jHAJH0eDsoiGnLPBlBp4TNm6rYI74nMzgz3B9IikW4WVK+dc8KZJZWYjAuORU3jc1c/NPskD2ASinf8v3xnfXeukU0sJ5N6m5E8VLjObPEO+mN2t/FZTMZLiFqPWc/ALSqnMnnhwrNi2rbfg/rd/IpL8Le3pSBne8+seeFVBoGqzHM9yXw==
            ' >> ~/.ssh/known_hosts
      - add_ssh_keys:
          fingerprints:
            - "b3:1e:03:cf:29:8b:36:a6:87:09:d9:a0:62:c6:97:fd"
      - github-ssh-key/checkup
    

workflows:
  github-ssh-key-deprecation:
    jobs:
      - check:
          matrix:
            parameters:
              docker-image:
                - circleci/node:14
                - circleci/node:16
                - circleci/node:12
                - circleci/python:3.8
                - circleci/python:3.9
                - circleci/golang:1.17
                - circleci/python:3.7
                - circleci/node:lts
                - circleci/node:16.13.0
                - circleci/openjdk:8-jdk
