version: 2.1

orbs:
  github-ssh-key: kelvintaywl/github-ssh-key-checkup@0.2

jobs:
  check:
    parameters:
      docker-image:
        type: string
    docker:
      - image: << parameters.docker-image >>
    resource_class: small
    steps:
      # NOTE: I chose not to checkout since CircleCI created an non-RSA deploy key by default,
      # and using checkout will check out this key into the system.
      # - checkout

      # Instead, I have added an RSA key as part of the project here,
      # and will check out this key instead.
      - add_ssh_keys:
          fingerprints:
            - "d2:ac:f1:0b:b9:78:7b:31:22:ee:41:75:1a:01:4b:04"
      - github-ssh-key/checkup
    

workflows:
  github-ssh-key-deprecation:
    jobs:
      - check:
          matrix:
            parameters:
              docker-image:
                - circleci/node:14
                - circleci/node:16
                - circleci/node:12
                - circleci/python:3.8
                - circleci/python:3.9
                - circleci/golang:1.17
                - circleci/python:3.7
                - circleci/node:lts
                - circleci/node:16.13.0
                - circleci/openjdk:8-jdk
